title: gem5 blog

remote_theme: just-the-docs/just-the-docs
color_scheme: dark

url: https://sangjae4309.github.io/docs-gem5

aux_links:
  Template Repository: https://github.com/sangjae4309/docs-gem5
