title: gem5
email: mainpower4309@gmail.com
permalink: /docs-gem5

# Build settings
#theme: "just-the-docs" # for local
remote_theme: just-the-docs/just-the-docs # for github
color_scheme: dark

# Callout definition
#callouts:
#  warning:
#    color: yellow
#  important:
#    color: blue
#  danger:
#    color: red
aux_links:
  Template Repository: https://github.com/sangjae4309/docs-gem5

