title: SANGJAE_PARK 
email: mainpower4309@gmail.com
description: # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: just-the-docs

# Callout definition
callouts:
  warning:
    color: yellow
  important:
    color: blue
  danger:
    color: red


